version: '3.6'

networks:
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}

services:
  node:
    container_name: ${DOCKER_NODE_CONTAINER_NAME}
    image: node:14-buster-slim
    expose:
      - ${DOCKER_NODE_PORT}
    ports:
      - ${DOCKER_NODE_PORT}:${DOCKER_NODE_PORT}
    environment:
      - NODE_ENV=production
    working_dir: /home/node
    volumes:
      - ./:/home/node:rw,cached
    command: sh -c "
      echo '\n\n\n\n' &&
      echo '---- NPM_REGISTRY -> ${DOCKER_NODE_NPM_REGISTRY} ----' &&
      echo '----  WORKING_DIR -> ${DOCKER_NODE_NPM_DISTURL} ----' &&
      echo '\n\n\n\n' &&
      yarn config set registry ${DOCKER_NODE_NPM_REGISTRY} &&
      yarn config set disturl ${DOCKER_NODE_NPM_DISTURL} &&
      yarn install --prod && yarn start"
