version: '3.6'

networks:
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}

services:
  node:
    container_name: ${__ENV__}_${DOCKER_NODE_CONTAINER_NAME}
    image: node:14-buster-slim
    expose:
      - ${DOCKER_NODE_PORT}
    ports:
      - ${DOCKER_NODE_PORT}:${DOCKER_NODE_PORT}
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node:rw,cached
      - ./.cache:/usr/local/share/.cache:rw,cached
      # `.cache` can greatly increase the speed of local yarn install. And does not affect the prod env.
    working_dir: /home/node
    command: sh -c "
      echo '\n\n' &&
      echo '__ENV__      -> ${__ENV__}\n' &&
      echo 'NPM_REGISTRY -> ${DOCKER_NODE_NPM_REGISTRY}' &&
      echo 'NPM_DISTURL  -> ${DOCKER_NODE_NPM_DISTURL}' &&
      echo '\n\n' &&
      yarn config set registry ${DOCKER_NODE_NPM_REGISTRY} &&
      yarn config set disturl ${DOCKER_NODE_NPM_DISTURL} &&
      echo '\n\n\n\n\n\n' &&
      ls -al &&
      echo '\n\n' &&
      yarn docker-start
      "
